server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    zookeeper:
      connect-string: localhost:2181
        #cloud:
        #gateway:
        #discovery:
        #locator:
      #enabled: true
logging:
  level:
    '[org.apache.zookeeper.ClientCnxn]': WARN
    #lower-case-service-id: true
